"""add agent_remarks to tasks

Revision ID: d5a56a9c08ca
Revises: 002
Create Date: 2026-02-22 16:43:25.507933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5a56a9c08ca'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'reputation_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('agents', 'avg_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idempotency_keys_agent_key_idx'), table_name='idempotency_keys')
    op.create_unique_constraint('idempotency_keys_agent_key_idx', 'idempotency_keys', ['agent_id', 'idempotency_key'])
    op.drop_index(op.f('reviews_task_id_unique'), table_name='reviews')
    op.create_unique_constraint('reviews_task_id_unique', 'reviews', ['task_id'])
    op.add_column('tasks', sa.Column('agent_remarks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'agent_remarks')
    op.drop_constraint('reviews_task_id_unique', 'reviews', type_='unique')
    op.create_index(op.f('reviews_task_id_unique'), 'reviews', ['task_id'], unique=True)
    op.drop_constraint('idempotency_keys_agent_key_idx', 'idempotency_keys', type_='unique')
    op.create_index(op.f('idempotency_keys_agent_key_idx'), 'idempotency_keys', ['agent_id', 'idempotency_key'], unique=True)
    op.alter_column('agents', 'avg_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('agents', 'reputation_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('50'))
    # ### end Alembic commands ###
